version: "3.8"

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress_dt:
    driver: "local"
    driver_opts:
      type: none
      device: "/home/medkhairallah/inception/data/wordpress"
      o: bind
  db_data:
    driver: "local"
    driver_opts:
      type: none
      device: "/home/medkhairallah/inception/data/mariadb"
      o: bind

services:
  nginx:
    container_name: "nginx"
    build: "./requirements/nginx/"
    env_file: .env
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
    volumes:
      - wordpress_dt:/var/www/html

  wordpress:
    container_name: "wordpress"
    build: "./requirements/wordpress/"
    env_file: .env
    networks:
      - inception
    depends_on:
      - mariadb
    expose:
      - 9000
    volumes:
      - wordpress_dt:/var/www/html
    restart: always

  mariadb:
    container_name: "mariadb"
    build: "./requirements/mariadb"
    env_file: .env
    expose:
      - 3306
    networks: 
      - inception
    volumes:
      - db_data:/var/lib/mysql
    restart: always
      