version: 3

  services:
    nginx:
      container_name: "nginx"
      build: "./requirements/nginx/"
      env_file: .env
      ports: 443:443
    wordpress:
      container_name: "wordpress"
      build: "./requirements/wordpress/"
      env_file: .env
    mariadb:
      container_name: "mariadb"
      build: "./requirements/mariadb"
      env_file: .env
      ports: 3306:3306

  volumes:
    wordpres: